### ISSUE TITLE
exec_spectral Cube Reprojection...rendered version is only showing the inputs

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/da5-notebooks#18]
The rendered version of the spectral-cube alignment by points notebook is only showing the inputs, not the outputs.

https://spacetelescope.github.io/notebooks-dev/notebooks/DATB/spectral_registration_manual/Spectral%20Cube%20Reprojection%20and%20Alignment%20by%20Manual%20Feature%20Selection.html

**Comment by hcferguson** [comment]
Likewise for the other one https://spacetelescope.github.io/notebooks-dev/notebooks/DATB/spectral_registration/Spectral%20Cube%20Reprojection%20and%20Alignment.html

**Comment by larrybradley** [comment]
This repo no longer creates rendered HTML versions of the notebooks.
